#!/bin/bash
set -e
cd /tmp/

MYSQL_HOST=$MYSQL_HOST
MYSQL_PORT=${MYSQL_PORT:-3306}
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWD=$MYSQL_PASSWD
MYSQL_DB=$MYSQL_DB
SQL_FILE=/home/nacos/conf/mysql-schema.sql

# Wait for MySQL check MYSQL_DB exist
while true; do
    mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWD -e "use $MYSQL_DB" && break
    echo "Waiting for MySQL service [$MYSQL_HOST:$MYSQL_PORT] to be ready..."
    sleep 5
done

# Check SQL file exist
if [ ! -f $SQL_FILE ]; then
    echo "SQL file $SQL_FILE not exist"
    exit 1
fi

# Import SQL file
mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWD}" -P"${MYSQL_PORT}" "${MYSQL_DB}" <"${SQL_FILE}" >/dev/null || {
  log "exec sql file failed."
  exit 30
}

# Init nacos user
SQL="INSERT INTO nacos.users (id, username, password, enabled) VALUES (1, 'nacos', '\$2a\$10\$WE53z00OLzek9ntSRg5SyOj4qnoqv62GR6Yr4zjxOibC7K0BqCTEq', TRUE);
INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');"
mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWD}" -P"${MYSQL_PORT}" "${MYSQL_DB}" -e "${SQL}"  >/dev/null || {
  log "insert sql file failed."
  exit 30
}